<<<<<<< HEAD
version: '3'

services:
  fastapi:
    build: fastapi/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    container_name: fastapi
    
  streamlit:
    build: streamlit/
    ports:
      - 8501:8501
    depends_on:
      - fastapi
    networks:
      - deply_network
    container_name: streamlit
=======
version: '3.8'

services:
  backend:
    build: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - app
    container_name: backend
    
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - app
    container_name: frontend
>>>>>>> 43f5170ff64629cbe5e0f23f5a3fa4a26383bde2
    


networks:
  app:
    driver: bridge