wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: resnet
dataset:
  desc: null
  value: dataset
epochs:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.7
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724674800
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.12.4
      5: 0.17.7
      8:
      - 3
      - 5
      13: windows-amd64
